export interface InfoTermsType {
  readonly seqNumber: string;
  rteType: string;
  procIdent: string;
  readonly transIdent: string;
  readonly fixIdent: string;
  readonly icaoCode: string;
  secCode: string;
  subCode: string;
  descCode: string;
  turnDr: string;
  readonly RNP: string;
  pathTerm: string;
  readonly tdv: string;
  readonly recdNavaid: string;
  readonly icaoCode2: string;
  readonly secCode2: string;
  readonly subCode2: string;
  readonly arcRadius: string;
  readonly theta: string;
  readonly rho: string;
  magCourse: string;
  readonly rteDistHoldTime: string;
  readonly altDesc: string;
  alt1: string;
  alt2: string;
  readonly transAlt: string;
  readonly spdLmtDisc: string;
  spdLimit: string;
  readonly vertAngle: string;
  readonly vertScaleFactor: string;
  readonly ctrFixIdent: string;
  readonly icaoCode3: string;
  readonly secCode3: string;
  readonly subCode3: string;
  readonly multicd: string;
  gnssFms: string;
  rteQual1: string;
  rteQual2: string;
}
