import { ColumnDef } from "@tanstack/react-table";
import { InfoTermsType } from "../../types/navDataTypes";

export const isHeaderEmpty = (
  header: keyof InfoTermsType,
  items: InfoTermsType[],
) => {
  return items.every((item) => {
    const value = item[header];
    const isValueEmpty =
      !value || /^[\s°ftkts;]*$/.test(value) || value === "°";
    return isValueEmpty;
  });
};

export const generateColumnsForInfoTermsType = (
  data: InfoTermsType[],
): ColumnDef<InfoTermsType>[] => {
  const headers = Array.from(
    new Set(
      data.flatMap((item) => Object.keys(item) as (keyof InfoTermsType)[]),
    ),
  ).filter((header) => !isHeaderEmpty(header, data));

  const autoGeneratedColumns = headers.map((key) => ({
    accessorKey: key,
  }));

  return [...autoGeneratedColumns];
};
